// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbacYCgRCg-ZtCU_YZsFrJVS5yldqjzIc',
    appId: '1:54391127653:web:ef967ef7717ad18da9508c',
    messagingSenderId: '54391127653',
    projectId: 'hmseggs3',
    authDomain: 'hmseggs3.firebaseapp.com',
    storageBucket: 'hmseggs3.firebasestorage.app',
    measurementId: 'G-EQP6FWF5TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3ewBCRnV8JrLGwAxgRn1niwLmZEH_7M',
    appId: '1:54391127653:android:a448222aefa15bdda9508c',
    messagingSenderId: '54391127653',
    projectId: 'hmseggs3',
    storageBucket: 'hmseggs3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv6gJ8XnxDS4VyOa4bdcVD56XWgCczUJc',
    appId: '1:54391127653:ios:bb6f44a2c999e3b9a9508c',
    messagingSenderId: '54391127653',
    projectId: 'hmseggs3',
    storageBucket: 'hmseggs3.firebasestorage.app',
    androidClientId: '54391127653-4mavu1m1eqvm96bqtrbike983qc38ev8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmsPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv6gJ8XnxDS4VyOa4bdcVD56XWgCczUJc',
    appId: '1:54391127653:ios:bb6f44a2c999e3b9a9508c',
    messagingSenderId: '54391127653',
    projectId: 'hmseggs3',
    storageBucket: 'hmseggs3.firebasestorage.app',
    androidClientId: '54391127653-4mavu1m1eqvm96bqtrbike983qc38ev8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmsPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbacYCgRCg-ZtCU_YZsFrJVS5yldqjzIc',
    appId: '1:54391127653:web:d13edc4b5e382fefa9508c',
    messagingSenderId: '54391127653',
    projectId: 'hmseggs3',
    authDomain: 'hmseggs3.firebaseapp.com',
    storageBucket: 'hmseggs3.firebasestorage.app',
    measurementId: 'G-MYRBY1NYRE',
  );
}
